# -*- coding: utf-8 -*-
"""NLP_HW1_NTHU_113012531.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CAkJBPd9z39p8VYcIQ3mu8gMIK3HTgN

## Part I: Data Pre-processing
"""

import pandas as pd

# Download the Google Analogy dataset
import requests
response = requests.get("http://download.tensorflow.org/data/questions-words.txt")

with open("questions-words.txt", "wb") as f:
    f.write(response.content)

print(f"檔案已下載並儲存為 questions-words.txt")

# Preprocess the dataset
file_name = "questions-words"
with open(f"{file_name}.txt", "r") as f:
    data = f.read().splitlines()

# check data from the first 10 entries
for entry in data[:10]:
    print(entry)

# TODO1: Write your code here for processing data to pd.DataFrame
# Please note that the first five mentions of ": " indicate `semantic`,
# and the remaining nine belong to the `syntatic` category.
import pandas as pd

questions = []
categories = []
sub_categories = []

section_count = 0
semantic_sections = 5  # semantic section number
current_section = None
current_category = None

for line in data:
    if line.startswith(":"):
        # section
        section_count += 1
        current_section = line[2:].strip()
        current_category = "semantic" if section_count <= semantic_sections else "syntactic"
    else:
        if line.strip():
            words = line.split()
            if len(words) == 4:
                question = " ".join(words)
                questions.append(question)
                categories.append(current_category)
                sub_categories.append(current_section)

# Create the dataframe
df = pd.DataFrame(
    {
        "Question": questions,
        "Category": categories,
        "SubCategory": sub_categories,
    }
)

df.head()

df.to_csv(f"{file_name}.csv", index=False)

"""## Part II: Use pre-trained word embeddings
- After finish Part I, you can run Part II code blocks only.
"""

import pandas as pd
import numpy as np
import gensim.downloader
from tqdm import tqdm
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from collections import defaultdict

data = pd.read_csv("questions-words.csv")

MODEL_NAME = "fasttext-wiki-news-subwords-300"
# You can try other models.
# https://radimrehurek.com/gensim/models/word2vec.html#pretrained-models

# Load the pre-trained model (using GloVe vectors here)
model = gensim.downloader.load(MODEL_NAME)
print("The Gensim model loaded successfully!")

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

for analogy in tqdm(data["Question"]):
    # TODO2: Write your code here to use pre-trained word embeddings for getting predictions of the analogy task.
    # You should also preserve the gold answers during iterations for evaluations later.
    """ Hints
    # Unpack the analogy (e.g., "man", "woman", "king", "queen")
    # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
    # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
    # Mikolov et al., 2013: big - biggest and small - smallest
    # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
    """
    # analogy: e.g. "man woman king queen"(以下analogy函式為詢問chatgpt進行)
    w1, w2, w3, w4 = analogy.split()

    # gold
    golds.append(w4)

    try:
        # 做向量運算：w2 - w1 + w3
        result = model.most_similar(
            positive=[w2, w3],
            negative=[w1],
            topn=1  # 只取最接近的一個詞
        )
        preds.append(result[0][0])
    except KeyError:
        # word not in vocab
        preds.append("<OOV>")



#由於使用範例model時Accuracy結果較差，詢問chatgpt可能的原因，chatgpt給出建議與架構先計算oov數量，確認是否是套用的model不符合dataset需求，導致向量計算不出
golds_np = np.array(preds)
preds_np = np.array(preds)

# 計算整體 OOV
total_oov = np.sum(preds_np == "<OOV>")
print(f"Total OOV words: {total_oov}, Fraction: {total_oov/len(preds_np):.2%}")

# 統計每個 Category / SubCategory 的 OOV 數量
categories_oov = defaultdict(int)
subcategories_oov = defaultdict(int)

for cat, subcat, pred in zip(data["Category"], data["SubCategory"], preds_np):
    if pred == "<OOV>":
        categories_oov[cat] += 1
        subcategories_oov[subcat] += 1

print("\nOOV by Category:")
for cat, count in categories_oov.items():
    print(f"{cat}: {count}")

print("\nOOV by SubCategory:")
for subcat, count in subcategories_oov.items():
    print(f"{subcat}: {count}")

# Perform evaluations. You do not need to modify this block!!

def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)

golds_np, preds_np = np.array(golds), np.array(preds)
data = pd.read_csv("questions-words.csv")

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category{sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = "family"

# TODO3: Plot t-SNE for the words in the SUB_CATEGORY `: family` (詢問chatgpt如何根據vector畫出tSNE，chatgpt提供基礎架構後再手動修改以符合自己的需要)

#先檢查整體oov數量
print(f"Total OOV words: {total_oov}, Fraction: {total_oov/len(preds_np):.2%}")# Collect words from Google Analogy dataset

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv("questions-words.csv")
subset = df[df["SubCategory"] == SUB_CATEGORY]["Question"]

# collect the only word
words = set()
for q in subset:
    words.update(q.split())
words = list(words)

# 過濾 OOV與檢查vector數 (遇到畫tSNE時報錯，chatgpt建議過濾掉OOV才可成功畫出)
vectors = []
valid_words = []
for w in words:
    try:
        vectors.append(model[w])
        valid_words.append(w)
    except KeyError:
        pass

vectors_np = np.array(vectors)

# 檢查樣本數(chatgpt建議增加檢測樣本數的步驟避免程式報錯)
n_samples = vectors_np.shape[0]
if n_samples < 2:
    raise ValueError("樣本數太少，無法做 t-SNE")

# 設定 perplexity，自動小於樣本數
perplexity_value = min(5, n_samples - 1)

# t-SNE 降維到 2D (chatgpt提供t-SNE plot code)
tsne = TSNE(
    n_components=2,
    random_state=42,
    init='pca',
    learning_rate='auto',
    perplexity=perplexity_value
)
vectors_2d = tsne.fit_transform(vectors_np)

plt.figure(figsize=(12, 8))
plt.scatter(vectors_2d[:, 0], vectors_2d[:, 1])

for i, word in enumerate(valid_words):
    plt.text(vectors_2d[i, 0]+0.1, vectors_2d[i, 1]+0.1, word, fontsize=9)


plt.title("Word Relationships from Google Analogy Task")
plt.savefig("word_relationships.png", bbox_inches="tight")
plt.show()

"""### Part III: Train your own word embeddings

### Get the latest English Wikipedia articles and do sampling.
- Usually, we start from Wikipedia dump (https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2). However, the downloading step will take very long. Also, the cleaning step for the Wikipedia corpus ([`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus)) will take much time. Therefore, we provide cleaned files for you.
"""

# Download the split Wikipedia files
# Each file contain 562365 lines (articles).(由chatgpt提供可在本地執行的檔案下載程式，無法下載則手動下載，替換!gdown)
import gdown
import os

folder = "wiki_data"
os.makedirs(folder, exist_ok=True)

files = {
    "1jiu9E1NalT2Y8EIuWNa1xf2Tw1f1XuGd": "wiki_texts_part_0.txt.gz",
    "1ABblLRd9HXdXvaNv8H9fFq984bhnowoG": "wiki_texts_part_1.txt.gz",
    "1z2VFNhpPvCejTP5zyejzKj5YjI_Bn42M": "wiki_texts_part_2.txt.gz",
    "1VKjded9BxADRhIoCzXy_W8uzVOTWIf0g": "wiki_texts_part_3.txt.gz",
    "16mBeG26m9LzHXdPe8UrijUIc6sHxhknz": "wiki_texts_part_4.txt.gz"
}

for file_id, filename in files.items():
    output_path = os.path.join(folder, filename)
    if not os.path.exists(output_path):
        gdown.download(f"https://drive.google.com/uc?id={file_id}", output_path, quiet=False)
    else:
        print(f"{filename} 已存在，跳過下載。")

print("所有檔案已下載完成")

# Download the split Wikipedia files
# Each file contain 562365 lines (articles), except the last file.

files = {
    "17JFvxOH-kc-VmvGkhG7p3iSZSpsWdgJI": "wiki_texts_part_5.txt.gz",
    "19IvB2vOJRGlrYulnTXlZECR8zT5v550P": "wiki_texts_part_6.txt.gz",
    "1sjwO8A2SDOKruv6-8NEq7pEIuQ50ygVV": "wiki_texts_part_7.txt.gz",
    "1s7xKWJmyk98Jbq6Fi1scrHy7fr_ellUX": "wiki_texts_part_8.txt.gz",
    "17eQXcrvY1cfpKelLbP2BhQKrljnFNykr": "wiki_texts_part_9.txt.gz",
    "1J5TAN6bNBiSgTIYiPwzmABvGhAF58h62": "wiki_texts_part_10.txt.gz"
}

# 下載檔案
for file_id, filename in files.items():
    output_path = os.path.join(folder, filename)
    if not os.path.exists(output_path):
        gdown.download(f"https://drive.google.com/uc?id={file_id}", output_path, quiet=False)
    else:
        print(f"{filename} 已存在，跳過下載。")

print("所有檔案處理完成")

# Extract the downloaded wiki_texts_parts files.(由chatgpt提供可在本地解壓code替換!gunzip)
import gzip
import shutil
import glob
import os

folder = "wiki_data"
gz_files = glob.glob(os.path.join(folder, "wiki_texts_part_*.gz"))

for gz_file in gz_files:
    output_file = gz_file[:-3]
    with gzip.open(gz_file, 'rb') as f_in:
        with open(output_file, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)
    print(f"已解壓: {output_file}")

print("所有檔案解壓完成")

# Combine the extracted wiki_texts_parts files.(由chatgpt提供可在本地合併code替換!cat)
import glob

folder = "wiki_data"
output_file =  "wiki_texts_combined1.txt"

# 找到所有解壓後的 txt 檔案，並排序（避免順序錯亂）
txt_files = sorted(glob.glob(os.path.join(folder, "wiki_texts_part_*.txt")))

with open(output_file, 'w', encoding='utf-8') as outfile:
    for txt_file in txt_files:
        with open(txt_file, 'r', encoding='utf-8') as infile:
            for line in infile:
                outfile.write(line)
        print(f"已合併: {txt_file}")

print(f"所有檔案已合併為 {output_file}")

# Check the first ten lines of the combined file (由chatgpt提供可在本地顯示前10 lines code替換!head)
file_path = "wiki_texts_combined.txt"
n = 10  # 顯示前 10 行

with open(file_path, 'r', encoding='utf-8') as f:
    for i in range(n):
        line = f.readline()
        if not line:
            break
        print(line.strip())

"""Please note that we used the default parameters of [`gensim.corpora.wikicorpus.WikiCorpus`](https://radimrehurek.com/gensim/corpora/wikicorpus.html#gensim.corpora.wikicorpus.WikiCorpus) for cleaning the Wiki raw file. Thus, words with one character were discarded."""

# Now you need to do sampling because the corpus is too big.
# You can further perform analysis with a greater sampling ratio.

import random
import os
wiki_txt_path = "wiki_texts_combined.txt"
output_path = "wiki_sampled_20.txt"
# wiki_texts_combined.txt is a text file separated by linebreaks (\n).
# Each row in wiki_texts_combined.txt indicates a Wikipedia article.




random.seed(42)
keep_prob = 0.2

with open(wiki_txt_path, "r", encoding="utf-8") as f:
    with open(output_path, "w", encoding="utf-8") as output_file:
    # TODO4: Sample `20%` Wikipedia articles
    # Write your code here
        for line in f:
            if random.random() < keep_prob:
                output_file.write(line)


with open(output_path, "r", encoding="utf-8") as f:
    total_lines = sum(1 for _ in f)

print(f"Total lines in sampled corpus: {total_lines}")

# TODO5: Train your own word embeddings with the sampled articles
# https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec
# Hint: You should perform some pre-processing before training.

# word2vec訓練結構包含preprocess,train參考:
# https://www.kaggle.com/code/jerrykuo7727/word2vec
# https://radimrehurek.com/gensim/models/word2vec.html
# 與chatgpt,再自行手動修改

import spacy
from gensim.models import Word2Vec
from tqdm import tqdm
import random
import os

# 1️.spaCy tokenizer
nlp = spacy.blank("en")  #此處詢問chatgpt較適合的tokenizer框架

# 2️.preprocess
input_file = "wiki_sampled_20.txt"
tokenized_file = "wiki_tokenized.txt"

def preprocess_and_save(input_file, output_file):
    with open(input_file, "r", encoding="utf-8") as f_in, \
         open(output_file, "w", encoding="utf-8") as f_out:
        for line in tqdm(f_in, total=total_lines, unit="lines", desc="Preprocessing"):
            line = line.strip()
            if not line:
                continue
            doc = nlp(line)
            tokens = []
            for token in doc:
                if token.is_alpha or token.is_digit or token.text in ["$", "€", "-"]:
                    tokens.append(token.text)
            if tokens:
                f_out.write(" ".join(tokens) + "\n")

if not os.path.exists(tokenized_file):
    print(f"{tokenized_file} 不存在，開始 preprocessing ...")
    preprocess_and_save(input_file, tokenized_file)
else:
    print(f"{tokenized_file} 已存在，直接使用")



# 3.TokenizedIterable（buffer shuffle），此處由於想降低記憶體消耗，chatgpt提供較有效率的架構：使用緩衝區批次讀取可以降低記憶體消耗 #詢問chatgpt shuffle的影響後決定shuffle
class TokenizedIterable:
    def __init__(self, filename, shuffle=False, buffer_size=20000):
        self.filename = filename
        self.shuffle = shuffle
        self.buffer_size = buffer_size

    def __iter__(self):
        buffer = []
        with open(self.filename, "r", encoding="utf-8") as f:
            for line in f:
                buffer.append(line.strip().split())
                if len(buffer) >= self.buffer_size:
                    if self.shuffle:
                        random.shuffle(buffer)
                    for tokens in buffer:
                        yield tokens
                    buffer = []

            if buffer:
                if self.shuffle:
                    random.shuffle(buffer)
                for tokens in buffer:
                    yield tokens



# 4.Building Word2Vec model
sentences = TokenizedIterable(tokenized_file, shuffle=True, buffer_size=20000)
model = Word2Vec(
    vector_size=300,
    window=5,
    min_count=2,
    workers=4,
    sg=1,
    sample=1e-4
)
model.build_vocab(sentences, progress_per=10000)


# 5.model training and most simmilar test
num_epochs = 10
for epoch in range(num_epochs):
    print(f"\n===== Epoch {epoch+1}/{num_epochs} =====")

    sentences_with_progress = tqdm(
        TokenizedIterable(tokenized_file, shuffle=True, buffer_size=20000),
        total=model.corpus_count,
        unit="sentences",
        desc=f"Training Epoch {epoch+1}"
    )

    model.train(
        sentences_with_progress,
        total_examples=model.corpus_count,
        epochs=1
    )

    if (epoch + 1) % 5 == 0:
        model.save(f"my_word2vec_epoch{epoch+1}.model")
        print(f"✅ Saved model at epoch {epoch+1}")

        try: #chatgpt提供如何在訓練過程中邊先測試accuracy&most similar to word
            accuracy, _ = model.wv.evaluate_word_analogies("questions-words.txt", restrict_vocab=30000)
            print(f"Analogy accuracy (restricted vocab=30k): {accuracy:.2%}")
        except Exception as e:
            print("Analogy test skipped:", e)

        if "king" in model.wv:
            print("Most similar to 'king':", model.wv.most_similar("king")[:5])
        else:
            print("'king' not in vocabulary")


# 6.model save
model.save("my_word2vec_final.model")
print(" Final model saved.")

import pandas as  pd

data = pd.read_csv("questions-words.csv")

from gensim.models import Word2Vec
from tqdm import tqdm
from collections import defaultdict
import pandas as pd

# Do predictions and preserve the gold answers (word_D)
preds = []
golds = []

model = Word2Vec.load("my_word2vec_final.model")
vocab = set(model.wv.index_to_key)

# 用於統計OOV在子類別的佔比
oov_count = 0
total_count = len(data)
category_oov = defaultdict(int)

preds = []
golds = []

for idx, row in tqdm(data.iterrows(), total=len(data)):
    # TODO6: Write your code here to use your trained word embeddings for getting predictions of the analogy task.
    # You should also preserve the gold answers during iterations for evaluations later.
    """ Hints
    # Unpack the analogy (e.g., "man", "woman", "king", "queen")
    # Perform vector arithmetic: word_b + word_c - word_a should be close to word_d
    # Source: https://github.com/piskvorky/gensim/blob/develop/gensim/models/keyedvectors.py#L776
    # Mikolov et al., 2013: big - biggest and small - smallest
    # Mikolov et al., 2013: X = vector(”biggest”) − vector(”big”) + vector(”small”).
    """
    w1, w2, w3, w4 = row["Question"].split()
    category = row["Category"]

    golds.append(w4)
    #由於使用範例model時Accuracy結果較差，詢問chatgpt可能的原因，chatgpt給出建議與架構先計算oov數量，確認是否是套用的model不符合dataset需求，導致向量計算不出
    if w1 not in vocab or w2 not in vocab or w3 not in vocab or w4 not in vocab:
        preds.append(None)
        oov_count += 1
        category_oov[category] += 1
        continue

    result = model.wv.most_similar(
        positive=[w2, w3],
        negative=[w1],
        topn=1
    )
    pred_word, score = result[0]
    preds.append(pred_word)

oov_ratio = oov_count / total_count
print(f"OOV count: {oov_count} / {total_count}, ratio: {oov_ratio:.2%}")

# 印出各類別 OOV 數量與比例
for cat, count in category_oov.items():
    cat_total = (data["Category"] == cat).sum()
    print(f"{cat}: {count}/{cat_total} ({count/cat_total:.2%})")

# Perform evaluations. You do not need to modify this block!!
import numpy as np
def calculate_accuracy(gold: np.ndarray, pred: np.ndarray) -> float:
    return np.mean(gold == pred)

golds_np, preds_np = np.array(golds), np.array(preds)
data = pd.read_csv("questions-words.csv")

# Evaluation: categories
for category in data["Category"].unique():
    mask = data["Category"] == category
    golds_cat, preds_cat = golds_np[mask], preds_np[mask]
    acc_cat = calculate_accuracy(golds_cat, preds_cat)
    print(f"Category: {category}, Accuracy: {acc_cat * 100}%")

# Evaluation: sub-categories
for sub_category in data["SubCategory"].unique():
    mask = data["SubCategory"] == sub_category
    golds_subcat, preds_subcat = golds_np[mask], preds_np[mask]
    acc_subcat = calculate_accuracy(golds_subcat, preds_subcat)
    print(f"Sub-Category{sub_category}, Accuracy: {acc_subcat * 100}%")

# Collect words from Google Analogy dataset
SUB_CATEGORY = "family"

# TODO7: Plot t-SNE for the words in the SUB_CATEGORY `: family`(詢問chatgpt如何根據vector畫出tSNE，chatgpt提供基礎架構後再手動修改以符合自己的需要)
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from gensim.models import Word2Vec

model = Word2Vec.load("my_word2vec_final.model")

# 讀取 questions-words.csv
df = pd.read_csv("questions-words.csv")
subset = df[df["SubCategory"] == SUB_CATEGORY]["Question"]

# collect the only word
words = set()
for q in subset:
    words.update(q.split())
words = list(words)

# 過濾 OOV與檢查vector數 (遇到畫tSNE時報錯，chatgpt建議過濾掉OOV才可成功畫出)
vectors = []
valid_words = []
for w in words:
    try:
        vectors.append(model.wv[w])
        valid_words.append(w)
    except KeyError:
        pass

vectors_np = np.array(vectors)
n_samples = vectors_np.shape[0]
if n_samples < 2:
    raise ValueError("樣本數太少，無法做 t-SNE")

perplexity_value = min(5, n_samples - 1)

# t-SNE
tsne = TSNE(n_components=2, random_state=42, init='pca', learning_rate='auto', perplexity=perplexity_value)
vectors_2d = tsne.fit_transform(vectors_np)

plt.figure(figsize=(12, 8))
plt.scatter(vectors_2d[:, 0], vectors_2d[:, 1])

for i, word in enumerate(valid_words):
    plt.text(vectors_2d[i, 0]+0.1, vectors_2d[i, 1]+0.1, word, fontsize=9)

plt.title("Word Relationships from Google Analogy Task - Family")
plt.savefig("word_relationships_family.png", bbox_inches="tight")
plt.show()

